version: '3.8'

services:
  # 1. Nosso Banco de Dados
  mysql:
    image: mysql:8.0
    container_name: diarias-ja-mysql
    environment:
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: verysecret
    ports:
      - "3300:3306" # Você acessa pelo 3300 no DBeaver/Workbench
    volumes:
      - mysql_data:/var/lib/mysql # Garante que os dados não sumam se o container cair

  # 2. Nosso Servidor de Cache
  redis:
    image: redis:alpine
    container_name: diarias-ja-redis
    ports:
      - "6379:6379"

  # 3. Nossa API Spring Boot
  backend:
    build: . # Manda o Docker ler o nosso Dockerfile
    container_name: diarias-ja-api
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - redis
    environment:
      # Sobrescrevemos as variáveis do application.yml com o nome dos containers!
      - DB_HOST=mysql
      - DB_PORT=3306 # Porta interna do Docker (e não a 3300)
      - DB_NAME=mydatabase
      - DB_USER=myuser
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - SHOW_SQL=true

volumes:
  mysql_data: