spring:
  application:
    name: diarias-ja-api
  
  # Conexão com o Banco de Dados (Preparado para o Amazon RDS)
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mydatabase}?createDatabaseIfNotExist=true
    username: ${DB_USER:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Conexão com o Redis (Preparado para o Amazon ElastiCache)
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  # Configuração do Hibernate (Ajustado para MySQL)
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: true